### ISSUE TITLE
ModuleNotFoundError: No module named 'openfst_python.pywrapfst' (1.6.9 branch )

### ISSUE THREAD

**Issue by onchiptech** [jpuigcerver/openfst-python#3]
I am trying to install openfst-python on Python 3.8.5. I've tried master branch as well as 1.6.9 branch, but none have worked. 

>>>>>>>>>>>>>>>>>>>>>>> master branch
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openfst_python as fst
>>> f=fst.Fst()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywrapfst.pyx", line 1617, in pywrapfst.Fst.__init__
AttributeError: 'pywrapfst.Fst' object has no attribute '_class__'

>>>>>>>>>>>>>>>>>>>>>>> 1.6.9 branch 

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openfst_python as fst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/surendra/d/projects/openfst-python/openfst_python/__init__.py", line 4, in <module>
    from openfst_python.pywrapfst import *
ModuleNotFoundError: No module named 'openfst_python.pywrapfst'

**Comment by onchiptech** [comment]
[solved] 1.6.9 branch works.
I've made a mistake...the error occurred because I imported openfst-python from the source folder.
